### ISSUE TITLE
can I change the input way ?!

### ISSUE THREAD

**Issue by abujbr** [chetbox/android-mouse-cursor#2]
Hi, i found your code while i'm dinging online, really helpful.

I would like to change the way I input the command so instead of using python script, I would like to use the Gyroscope to move that cursor, but each time I  try to inject the code with direct command it crash !!
`   public void onSensorEvent (SensorEvent event) {
        cursorLayout.x = cursorLayout.x - (int) event.values[0];
        cursorLayout.y = cursorLayout.y + (int) event.values[1];
            if (cursorLayout.x <=  20) {
                cursorLayout.x =  20;
              
            }
            if (cursorLayout.x >= 10 - 20) {
                cursorLayout.x = 10 - 20;

            }
            if (cursorLayout.y<=  20) {
                cursorLayout.y =  20;

            }
            if (cursorLayout.y >= 10 - 20) {
                cursorLayout.y = 10 - 20;

            }

        windowManager.updateViewLayout(cursorView, cursorLayout);
    }`

thanks in advance

**Comment by abujbr** [comment]
to be more clear each time i give cursorLayout  X or Y a value it give me NullpointerExeption 
![nullpointerexception](https://user-images.githubusercontent.com/8819242/26895744-25608f0c-4bf5-11e7-8b97-85d0309bca4a.jpg)

**Comment by chetbox** [comment]
You just need to make sure you set your sensor listener at the end of `onCreate`, after `cursorLayout` has been set.

**Comment by abujbr** [comment]
thank you so much , it work perfectly :)
